name: Create and publish container image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: chatterbox-tts
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner}}
  IMAGE_TAGS: latest ${{ github.ref_name }} ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multiarch)
        uses: docker/setup-qemu-action@v3.6.0

      - name: Build and push multiarch image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/amd64,linux/arm64

      - name: Push to GHCR
        id: push
        uses: redhat-actions/push-to-registry@...
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: --disable-content-trust

      - name: Print outputs
        run: echo "${{ toJSON(steps.push.outputs) }}"
